//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _CODELITE_DIARYGUI_WXCRAFTER_BASE_CLASSES_H
#define _CODELITE_DIARYGUI_WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/menu.h>
#include <wx/button.h>
#include <wx/stattext.h>
#include <wx/listctrl.h>
#include <wx/choice.h>
#include <wx/arrstr.h>
#include <wx/textctrl.h>
#include <wx/checkbox.h>
#include <wx/calctrl.h>
#include <wx/statbox.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class MainFrameBaseClass : public wxFrame
{
protected:
    wxMenuBar* m_menuBar;
    wxMenu* m_name6;
    wxMenuItem* m_menuItem7;
    wxMenu* m_name8;
    wxMenuItem* m_menuItem9;
    wxButton* button_addBoard;
    wxStaticText* text1;
    wxStaticText* text2;
    wxStaticText* text3;
    wxListCtrl* list1;
    wxListCtrl* list2;
    wxListCtrl* list3;
    wxButton* button_rename1;
    wxButton* button_add1;
    wxButton* button_delete1;
    wxButton* button_rename2;
    wxButton* button_add2;
    wxButton* button_delete2;
    wxButton* button_rename3;
    wxButton* button_add3;
    wxButton* button_delete3;
    wxButton* button_back;
    wxButton* button_forward;

protected:
    virtual void OnExit(wxCommandEvent& event) { event.Skip(); }
    virtual void OnAbout(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_addboardButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnList1ListItemActivated(wxListEvent& event) { event.Skip(); }
    virtual void OnList1ListItemSelected(wxListEvent& event) { event.Skip(); }
    virtual void OnList1ListBeginDrag(wxListEvent& event) { event.Skip(); }
    virtual void OnList2ListItemActivated(wxListEvent& event) { event.Skip(); }
    virtual void OnList2ListItemSelected(wxListEvent& event) { event.Skip(); }
    virtual void OnList2ListBeginDrag(wxListEvent& event) { event.Skip(); }
    virtual void OnList3ListItemActivated(wxListEvent& event) { event.Skip(); }
    virtual void OnList3ListItemSelected(wxListEvent& event) { event.Skip(); }
    virtual void OnList3ListBeginDrag(wxListEvent& event) { event.Skip(); }
    virtual void OnButton_rename1ButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_add1ButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_delete1ButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_rename2ButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_add2ButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_delete2ButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_rename3ButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_add3ButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_delete3ButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_backButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_forwardButtonClicked(wxCommandEvent& event) { event.Skip(); }

public:
    wxMenuBar* GetMenuBar() { return m_menuBar; }
    wxButton* GetButton_addBoard() { return button_addBoard; }
    wxStaticText* GetText1() { return text1; }
    wxStaticText* GetText2() { return text2; }
    wxStaticText* GetText3() { return text3; }
    wxListCtrl* GetList1() { return list1; }
    wxListCtrl* GetList2() { return list2; }
    wxListCtrl* GetList3() { return list3; }
    wxButton* GetButton_rename1() { return button_rename1; }
    wxButton* GetButton_add1() { return button_add1; }
    wxButton* GetButton_delete1() { return button_delete1; }
    wxButton* GetButton_rename2() { return button_rename2; }
    wxButton* GetButton_add2() { return button_add2; }
    wxButton* GetButton_delete2() { return button_delete2; }
    wxButton* GetButton_rename3() { return button_rename3; }
    wxButton* GetButton_add3() { return button_add3; }
    wxButton* GetButton_delete3() { return button_delete3; }
    wxButton* GetButton_back() { return button_back; }
    wxButton* GetButton_forward() { return button_forward; }
    MainFrameBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("My Frame"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxCAPTION|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU|wxCLOSE_BOX);
    virtual ~MainFrameBaseClass();
};


class DiaryHomeBase : public wxFrame
{
protected:
    wxButton* button_addBoard;
    wxChoice* selecter;
    wxButton* button_accept;

protected:
    virtual void OnButton_addboardButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_acceptButtonClicked(wxCommandEvent& event) { event.Skip(); }

public:
    wxButton* GetButton_addBoard() { return button_addBoard; }
    wxChoice* GetSelecter() { return selecter; }
    wxButton* GetButton_accept() { return button_accept; }
    DiaryHomeBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Diary"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_FRAME_STYLE);
    virtual ~DiaryHomeBase();
};


class NewBoardBase : public wxFrame
{
protected:
    wxStaticText* m_staticText69;
    wxTextCtrl* text_boardName;
    wxButton* button_addBoard;

protected:
    virtual void OnButton_addboardButtonClicked(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText69() { return m_staticText69; }
    wxTextCtrl* GetText_boardName() { return text_boardName; }
    wxButton* GetButton_addBoard() { return button_addBoard; }
    NewBoardBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Diary: Aggiungi Bacheca"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxCLOSE_BOX|wxSTAY_ON_TOP);
    virtual ~NewBoardBase();
};


class AddActivityBase : public wxFrame
{
protected:
    wxStaticText* Titolo;
    wxTextCtrl* text_title;
    wxStaticText* m_staticText109;
    wxTextCtrl* text_description;
    wxStaticText* m_staticText113;
    wxCheckBox* check_deadline;
    wxCalendarCtrl* calendar;
    wxButton* buttom_confirm;

protected:
    virtual void OnCheck_deadlineCheckboxClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButtoconfirmButtonClicked(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetTitolo() { return Titolo; }
    wxTextCtrl* GetText_title() { return text_title; }
    wxStaticText* GetStaticText109() { return m_staticText109; }
    wxTextCtrl* GetText_description() { return text_description; }
    wxStaticText* GetStaticText113() { return m_staticText113; }
    wxCheckBox* GetCheck_deadline() { return check_deadline; }
    wxCalendarCtrl* GetCalendar() { return calendar; }
    wxButton* GetButtom_confirm() { return buttom_confirm; }
    AddActivityBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Diary: Aggiungi attività"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_FRAME_STYLE);
    virtual ~AddActivityBase();
};


class ActivityDetailsBase : public wxFrame
{
protected:
    wxStaticText* m_staticText133;
    wxTextCtrl* text_title;
    wxStaticText* m_staticText137;
    wxTextCtrl* text_description;
    wxStaticText* m_staticText141;
    wxCalendarCtrl* calendar_modify;
    wxCheckBox* check_modify;
    wxButton* button_modifyconfirm;
    wxListCtrl* list_person;
    wxButton* button_addPerson;
    wxButton* button_removePerson;
    wxListCtrl* list_subActivity;
    wxButton* buttom_addSubActivity;
    wxButton* button_removeSubActivity;

protected:
    virtual void OnCheck_modifyCheckboxClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_modifyconfirmButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnList_personListItemSelected(wxListEvent& event) { event.Skip(); }
    virtual void OnButton_addpersonButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_removepersonButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnList_subactivityListItemSelected(wxListEvent& event) { event.Skip(); }
    virtual void OnButtoaddsubactivityButtonClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnButton_removesubactivityButtonClicked(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText133() { return m_staticText133; }
    wxTextCtrl* GetText_title() { return text_title; }
    wxStaticText* GetStaticText137() { return m_staticText137; }
    wxTextCtrl* GetText_description() { return text_description; }
    wxStaticText* GetStaticText141() { return m_staticText141; }
    wxCalendarCtrl* GetCalendar_modify() { return calendar_modify; }
    wxCheckBox* GetCheck_modify() { return check_modify; }
    wxButton* GetButton_modifyconfirm() { return button_modifyconfirm; }
    wxListCtrl* GetList_person() { return list_person; }
    wxButton* GetButton_addPerson() { return button_addPerson; }
    wxButton* GetButton_removePerson() { return button_removePerson; }
    wxListCtrl* GetList_subActivity() { return list_subActivity; }
    wxButton* GetButtom_addSubActivity() { return buttom_addSubActivity; }
    wxButton* GetButton_removeSubActivity() { return button_removeSubActivity; }
    ActivityDetailsBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Diary: Nome Attività"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_FRAME_STYLE);
    virtual ~ActivityDetailsBase();
};


class AddPersonBase : public wxFrame
{
protected:
    wxStaticText* m_staticText186;
    wxTextCtrl* textFirstName;
    wxStaticText* m_staticText190;
    wxTextCtrl* textLastName;
    wxButton* button_confirmPerson;

protected:
    virtual void OnButton_confirmpersonButtonClicked(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText186() { return m_staticText186; }
    wxTextCtrl* GetTextFirstName() { return textFirstName; }
    wxStaticText* GetStaticText190() { return m_staticText190; }
    wxTextCtrl* GetTextLastName() { return textLastName; }
    wxButton* GetButton_confirmPerson() { return button_confirmPerson; }
    AddPersonBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Diary: Aggiungi persona"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxCAPTION|wxCLOSE_BOX|wxSTAY_ON_TOP);
    virtual ~AddPersonBase();
};


class AddSubActivityBase : public wxFrame
{
protected:
    wxStaticText* m_staticText202;
    wxTextCtrl* textTitle;
    wxStaticText* m_staticText206;
    wxTextCtrl* textDescription;
    wxButton* button_confirmSubActivity;

protected:
    virtual void OnButton_confirmsubactivityButtonClicked(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText202() { return m_staticText202; }
    wxTextCtrl* GetTextTitle() { return textTitle; }
    wxStaticText* GetStaticText206() { return m_staticText206; }
    wxTextCtrl* GetTextDescription() { return textDescription; }
    wxButton* GetButton_confirmSubActivity() { return button_confirmSubActivity; }
    AddSubActivityBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Diary: Aggiungi sottoattività"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxCAPTION|wxCLOSE_BOX|wxSTAY_ON_TOP);
    virtual ~AddSubActivityBase();
};


class AddActivityListBase : public wxFrame
{
protected:
    wxStaticText* m_staticText218;
    wxTextCtrl* textAddActivityList;
    wxButton* buttonConfirm_ActivityList;

protected:
    virtual void OnButtonConfirmActivityListButtonClicked(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText218() { return m_staticText218; }
    wxTextCtrl* GetTextAddActivityList() { return textAddActivityList; }
    wxButton* GetButtonConfirm_ActivityList() { return buttonConfirm_ActivityList; }
    AddActivityListBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Diary: Aggiungi lista attività"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxCAPTION|wxCLOSE_BOX|wxSTAY_ON_TOP);
    virtual ~AddActivityListBase();
};

#endif
